# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attendance_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttendanceItem(object):
    def setupUi(self, AttendanceItem):
        AttendanceItem.setObjectName("AttendanceItem")
        AttendanceItem.resize(300, 90)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(AttendanceItem)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.name_lbl = QtWidgets.QLabel(AttendanceItem)
        self.name_lbl.setObjectName("name_lbl")
        self.horizontalLayout_2.addWidget(self.name_lbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.face_img = QtWidgets.QLabel(AttendanceItem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.face_img.sizePolicy().hasHeightForWidth())
        self.face_img.setSizePolicy(sizePolicy)
        self.face_img.setMinimumSize(QtCore.QSize(66, 0))
        self.face_img.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.face_img.setText("")
        self.face_img.setObjectName("face_img")
        self.horizontalLayout.addWidget(self.face_img)
        self.match_layout = QtWidgets.QHBoxLayout()
        self.match_layout.setObjectName("match_layout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.match_lbl = QtWidgets.QLabel(AttendanceItem)
        self.match_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.match_lbl.setObjectName("match_lbl")
        self.verticalLayout.addWidget(self.match_lbl)
        self.similar_degree_lbl = QtWidgets.QLabel(AttendanceItem)
        self.similar_degree_lbl.setStyleSheet("color: rgb(255, 0, 0);")
        self.similar_degree_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.similar_degree_lbl.setObjectName("similar_degree_lbl")
        self.verticalLayout.addWidget(self.similar_degree_lbl)
        self.match_layout.addLayout(self.verticalLayout)
        self.matched_face_img = QtWidgets.QLabel(AttendanceItem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.matched_face_img.sizePolicy().hasHeightForWidth())
        self.matched_face_img.setSizePolicy(sizePolicy)
        self.matched_face_img.setMinimumSize(QtCore.QSize(66, 0))
        self.matched_face_img.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.matched_face_img.setText("")
        self.matched_face_img.setObjectName("matched_face_img")
        self.match_layout.addWidget(self.matched_face_img)
        self.horizontalLayout.addLayout(self.match_layout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(AttendanceItem)
        QtCore.QMetaObject.connectSlotsByName(AttendanceItem)

    def retranslateUi(self, AttendanceItem):
        _translate = QtCore.QCoreApplication.translate
        AttendanceItem.setWindowTitle(_translate("AttendanceItem", "AttendanceItem"))
        self.name_lbl.setText(_translate("AttendanceItem", "未命名"))
        self.match_lbl.setText(_translate("AttendanceItem", "匹配"))
        self.similar_degree_lbl.setText(_translate("AttendanceItem", "0.0%"))
