# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cheating_list_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CheatingListItem(object):
    def setupUi(self, CheatingListItem):
        CheatingListItem.setObjectName("CheatingListItem")
        CheatingListItem.setWindowModality(QtCore.Qt.NonModal)
        CheatingListItem.setEnabled(True)
        CheatingListItem.resize(196, 41)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CheatingListItem)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl = QtWidgets.QLabel(CheatingListItem)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(7)
        self.lbl.setFont(font)
        self.lbl.setMouseTracking(False)
        self.lbl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl.setLineWidth(0)
        self.lbl.setTextFormat(QtCore.Qt.RichText)
        self.lbl.setOpenExternalLinks(False)
        self.lbl.setObjectName("lbl")
        self.horizontalLayout.addWidget(self.lbl)

        self.retranslateUi(CheatingListItem)
        QtCore.QMetaObject.connectSlotsByName(CheatingListItem)

    def retranslateUi(self, CheatingListItem):
        _translate = QtCore.QCoreApplication.translate
        CheatingListItem.setWindowTitle(_translate("CheatingListItem", "cheating_list_item"))
        self.lbl.setText(_translate("CheatingListItem", "lbl"))
