# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'face_list_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FaceListItem(object):
    def setupUi(self, FaceListItem):
        FaceListItem.setObjectName("FaceListItem")
        FaceListItem.resize(117, 154)
        FaceListItem.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(9)
        FaceListItem.setFont(font)
        FaceListItem.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(FaceListItem)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.face_img = QtWidgets.QLabel(FaceListItem)
        self.face_img.setMinimumSize(QtCore.QSize(95, 95))
        self.face_img.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.face_img.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.face_img.setText("")
        self.face_img.setAlignment(QtCore.Qt.AlignCenter)
        self.face_img.setOpenExternalLinks(False)
        self.face_img.setObjectName("face_img")
        self.verticalLayout.addWidget(self.face_img)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_lbl = QtWidgets.QLabel(FaceListItem)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(9)
        self.name_lbl.setFont(font)
        self.name_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.name_lbl.setObjectName("name_lbl")
        self.horizontalLayout.addWidget(self.name_lbl)
        self.edit_name_btn = QtWidgets.QPushButton(FaceListItem)
        self.edit_name_btn.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.edit_name_btn.setText("")
        self.edit_name_btn.setObjectName("edit_name_btn")
        self.horizontalLayout.addWidget(self.edit_name_btn)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(FaceListItem)
        QtCore.QMetaObject.connectSlotsByName(FaceListItem)

    def retranslateUi(self, FaceListItem):
        _translate = QtCore.QCoreApplication.translate
        FaceListItem.setWindowTitle(_translate("FaceListItem", "face_list_item"))
        self.name_lbl.setText(_translate("FaceListItem", "未命名"))
