# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'real_time_catch.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RealTimeCatch(object):
    def setupUi(self, RealTimeCatch):
        RealTimeCatch.setObjectName("RealTimeCatch")
        RealTimeCatch.resize(200, 200)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(7)
        RealTimeCatch.setFont(font)
        RealTimeCatch.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(RealTimeCatch)
        self.verticalLayout.setObjectName("verticalLayout")
        self.catch_img = QtWidgets.QLabel(RealTimeCatch)
        self.catch_img.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.catch_img.setText("")
        self.catch_img.setObjectName("catch_img")
        self.verticalLayout.addWidget(self.catch_img)
        self.time_lbl = QtWidgets.QLabel(RealTimeCatch)
        self.time_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.time_lbl.setObjectName("time_lbl")
        self.verticalLayout.addWidget(self.time_lbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(RealTimeCatch)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cheating_type_lbl = QtWidgets.QLabel(RealTimeCatch)
        self.cheating_type_lbl.setText("")
        self.cheating_type_lbl.setObjectName("cheating_type_lbl")
        self.horizontalLayout.addWidget(self.cheating_type_lbl)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 8)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)

        self.retranslateUi(RealTimeCatch)
        QtCore.QMetaObject.connectSlotsByName(RealTimeCatch)

    def retranslateUi(self, RealTimeCatch):
        _translate = QtCore.QCoreApplication.translate
        RealTimeCatch.setWindowTitle(_translate("RealTimeCatch", "real_time_catch"))
        self.time_lbl.setText(_translate("RealTimeCatch", "00:00:00"))
        self.label.setText(_translate("RealTimeCatch", "行为:"))
