# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'smart_classroom.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 824)
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        icon = QtGui.QIcon.fromTheme("window_icon")
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("font: 10pt \"华文琥珀\";\n"
"QPushButton\n"
"                     {text-align : center;\n"
"                     background-color : white;\n"
"                     font: bold;\n"
"                     border-color: ;\n"
"    color: rgb(255, 255, 255);\n"
"                     border-width: 5px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"                     QPushButton:pressed\n"
"                     {text-align : center;\n"
"                     background-color : light gray;\n"
"                     font: bold;\n"
"                     border-color: gray;\n"
"                     border-width: 2px;\n"
"                     border-radius: 10px;\n"
"                     padding: 6px;\n"
"                     height : 14px;\n"
"                     border-style: outset;\n"
"                     font : 14px;}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.verticalLayout_7.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_cheating_detection = QtWidgets.QAction(MainWindow)
        self.action_cheating_detection.setObjectName("action_cheating_detection")
        self.action_class_focus = QtWidgets.QAction(MainWindow)
        self.action_class_focus.setObjectName("action_class_focus")
        self.about_us = QtWidgets.QAction(MainWindow)
        self.about_us.setObjectName("about_us")
        self.menu.addAction(self.action_cheating_detection)
        self.menu.addSeparator()
        self.menu.addAction(self.action_class_focus)
        self.menu_3.addAction(self.about_us)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智慧教室"))
        self.menu.setTitle(_translate("MainWindow", "主要功能"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.menu_3.setTitle(_translate("MainWindow", "帮助"))
        self.action_cheating_detection.setText(_translate("MainWindow", "作弊检测"))
        self.action_class_focus.setText(_translate("MainWindow", "课堂专注度分析"))
        self.about_us.setText(_translate("MainWindow", "关于我们"))
